# Generated by Django 5.2.14 on 2026-05-14 17:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_venues', to='camps.camp')),
                ('coaches', models.ManyToManyField(blank=True, related_name='assessment_venues', to='camps.coach')),
            ],
            options={
                'ordering': ['camp', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_assignment', to='camps.campenrollment')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='assessments.assessmentvenue')),
            ],
            options={
                'ordering': ['venue', 'enrollment__nickname'],
            },
        ),
        migrations.CreateModel(
            name='EntranceAssessmentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('viewpoint', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='观点生产')),
                ('personality', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='个性张力')),
                ('emotion', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='情感传达')),
                ('reasoning', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='事理表述')),
                ('clash', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='攻防交锋')),
                ('note', models.TextField(blank=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='assessments.assessmentassignment')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entrance_scores', to='camps.coach')),
            ],
            options={
                'ordering': ['assignment', 'coach__name'],
            },
        ),
        migrations.CreateModel(
            name='GraduationEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('viewpoint', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='观点生产')),
                ('personality', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='个性张力')),
                ('emotion', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='情感传达')),
                ('reasoning', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='事理表述')),
                ('clash', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='攻防交锋')),
                ('viewpoint_text', models.TextField(blank=True, verbose_name='观点生产评价')),
                ('personality_text', models.TextField(blank=True, verbose_name='个性张力评价')),
                ('emotion_text', models.TextField(blank=True, verbose_name='情感传达评价')),
                ('reasoning_text', models.TextField(blank=True, verbose_name='事理表述评价')),
                ('clash_text', models.TextField(blank=True, verbose_name='攻防交锋评价')),
                ('message', models.TextField(blank=True, verbose_name='结营寄语')),
                ('exported_image', models.ImageField(blank=True, upload_to='graduation_exports/')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='graduation_evaluations', to='camps.coach')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='graduation_evaluation', to='camps.campenrollment')),
            ],
            options={
                'ordering': ['enrollment__camp', 'enrollment__team__name', 'enrollment__nickname'],
            },
        ),
        migrations.AddConstraint(
            model_name='assessmentvenue',
            constraint=models.UniqueConstraint(fields=('camp', 'name'), name='unique_assessment_venue_per_camp'),
        ),
        migrations.AddConstraint(
            model_name='entranceassessmentscore',
            constraint=models.UniqueConstraint(fields=('assignment', 'coach'), name='unique_entrance_score_per_coach'),
        ),
    ]
