# Generated by Django 5.2.14 on 2026-05-14 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('season', models.CharField(blank=True, max_length=60)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-starts_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('real_name', models.CharField(max_length=80)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['real_name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='camps.camp')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='camps.coach')),
            ],
            options={
                'ordering': ['camp', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CampEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nickname', models.CharField(max_length=80)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='camps.camp')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='camp_enrollments', to='camps.student')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='camps.team')),
            ],
            options={
                'ordering': ['camp', 'team__name', 'nickname'],
            },
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('camp', 'name'), name='unique_team_name_per_camp'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('camp', 'coach'), name='unique_coach_team_per_camp'),
        ),
        migrations.AddConstraint(
            model_name='campenrollment',
            constraint=models.UniqueConstraint(fields=('camp', 'student'), name='unique_student_per_camp'),
        ),
        migrations.AddConstraint(
            model_name='campenrollment',
            constraint=models.UniqueConstraint(fields=('camp', 'nickname'), name='unique_nickname_per_camp'),
        ),
    ]
