# Generated by Django 5.2.14 on 2026-05-14 17:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebatePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('side', models.CharField(choices=[('affirmative', '正方'), ('negative', '反方')], max_length=20)),
                ('position_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('coach_note', models.TextField(blank=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debate_positions', to='camps.campenrollment')),
            ],
            options={
                'ordering': ['match', 'side', 'position_number'],
            },
        ),
        migrations.CreateModel(
            name='IntegralRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integral_rounds', to='camps.camp')),
            ],
            options={
                'ordering': ['camp', 'number'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('judges', models.ManyToManyField(blank=True, related_name='competition_venues', to='camps.judge')),
                ('integral_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='competitions.integralround')),
            ],
            options={
                'ordering': ['integral_round', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JudgeBallot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affirmative_votes', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('negative_votes', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('corrected_by_staff', models.BooleanField(default=False)),
                ('correction_note', models.TextField(blank=True)),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ballots', to='camps.judge')),
            ],
            options={
                'ordering': ['match', 'judge__name'],
            },
        ),
        migrations.CreateModel(
            name='BestSpeakerVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weight', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_speaker_votes', to='competitions.debateposition')),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_speaker_votes', to='competitions.judgeballot')),
            ],
            options={
                'ordering': ['ballot', '-weight'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('starts_at', models.TimeField()),
                ('affirmative_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affirmative_matches', to='camps.team')),
                ('best_speaker_override', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_speaker_override_matches', to='competitions.debateposition')),
                ('integral_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='competitions.integralround')),
                ('negative_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='negative_matches', to='camps.team')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='competitions.competitionvenue')),
            ],
            options={
                'ordering': ['integral_round', 'venue__name', 'sequence'],
            },
        ),
        migrations.AddField(
            model_name='judgeballot',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='competitions.match'),
        ),
        migrations.AddField(
            model_name='debateposition',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='competitions.match'),
        ),
        migrations.CreateModel(
            name='PositionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('speech_record', models.TextField(blank=True)),
                ('judge_feedback', models.TextField(blank=True)),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_scores', to='competitions.judgeballot')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='competitions.debateposition')),
            ],
            options={
                'ordering': ['ballot', 'position__side', 'position__position_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='integralround',
            constraint=models.UniqueConstraint(fields=('camp', 'number'), name='unique_integral_round_per_camp'),
        ),
        migrations.AddConstraint(
            model_name='competitionvenue',
            constraint=models.UniqueConstraint(fields=('integral_round', 'name'), name='unique_competition_venue_per_round'),
        ),
        migrations.AddConstraint(
            model_name='bestspeakervote',
            constraint=models.UniqueConstraint(fields=('ballot', 'weight'), name='unique_best_speaker_weight_per_ballot'),
        ),
        migrations.AddConstraint(
            model_name='bestspeakervote',
            constraint=models.UniqueConstraint(fields=('ballot', 'position'), name='unique_best_speaker_position_per_ballot'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('venue', 'sequence'), name='unique_match_sequence_per_venue'),
        ),
        migrations.AddConstraint(
            model_name='judgeballot',
            constraint=models.UniqueConstraint(fields=('match', 'judge'), name='unique_ballot_per_match_judge'),
        ),
        migrations.AddConstraint(
            model_name='debateposition',
            constraint=models.UniqueConstraint(fields=('match', 'side', 'position_number'), name='unique_position_per_match_side'),
        ),
        migrations.AddConstraint(
            model_name='positionscore',
            constraint=models.UniqueConstraint(fields=('ballot', 'position'), name='unique_position_score_per_ballot'),
        ),
    ]
